name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Dispatch Deploy Event
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Trigger Repository Dispatch Event
        run: |
          echo "Triggering repository dispatch event for 'deploy'..."
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/viseshrp/todayilearned/dispatches \
            -d '{"event_type":"deploy"}'
